--liquibase formatted sql

--changeset leto:61
CREATE TABLE user_tg
(
    id       BIGINT generated by default as identity primary key,
    name     TEXT   not null,
    msg_numb int not null

);

CREATE TABLE message_tg
(
    id       BIGINT generated by default as identity primary key,
    date_time timestamp not null,
    user_id BIGINT references user_tg (id) on delete set null
);